[build]
  publish = "."

[[redirects]]
  from = "/delete"
  to = "/delete-account.html"
  status = 200

[[redirects]]
  from = "/account-deletion"
  to = "/delete-account.html"
  status = 200

[[redirects]]
  from = "/delete-account"
  to = "/delete-account.html"
  status = 200
